# Copyright 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0
build = 'Soong'

[[project_config]]
name = 'android_aarch64_drivers'

[project_config.host_machine]
cpu_family = 'aarch64'
cpu = 'aarch64'
host_machine = 'android'
build_machine = 'linux'

[project_config.meson_options]
platforms = 'android'
android-libbacktrace = 'disabled'
gallium-drivers = ''
vulkan-drivers = 'freedreno'
freedreno-kmds = 'kgsl'
platform-sdk-version = 33

[project_config.header_not_supported]
headers = []

[project_config.symbol_not_supported]
symbols = []

[project_config.function_not_supported]
functions = []

[project_config.link_not_supported]
links = []

[project_config.ext_dependencies]
# DependencyTargetType
#   SHARED_LIBRARY = 1
#   STATIC_LIBRARY = 2
#   HEADER_LIBRARY = 3
# See meson_impl.py
zlib = [
    { target_name = 'libz', target_type = 2 }
]
hardware = [
    { target_name = 'libhardware', target_type = 1 },
    { target_name = 'hwvulkan_headers', target_type = 3 }
]
cutils = [
    { target_name = 'libcutils', target_type = 1 }
]
log = [
    { target_name = 'liblog', target_type = 1 }
]
nativewindow = [
    { target_name = 'libnativewindow', target_type = 1 }
]
sync = [
    { target_name = 'libsync', target_type = 2 }
]
'android.hardware.graphics.mapper' = [
    { target_name = 'libgralloctypes', target_type = 2 },
    { target_name = 'android.hardware.graphics.mapper@4.0', target_type = 2 },
    { target_name = 'libhidlbase', target_type = 1 },
    { target_name = 'libutils', target_type = 1 }
]

# Define new project configs
# [[project_config]]
