# Copyright 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0
build = 'bazel'

[[project_config]]
name = 'fuchsia_aarch64_drivers'

[[project_config.host_machine]]
cpu_family = 'aarch64'
cpu = 'aarch64'

[[project_config.meson_options]]
platforms = 'none'
gallium-drivers = ''
vulkan-drivers = 'freedreno'
freedreno-kmds = 'magma'
platform-sdk-version = 33
shader-cache = 'disabled'

[[project_config.ext_dependencies]]
# DependencyTargetType
#   SHARED_LIBRARY = 1
#   STATIC_LIBRARY = 2
#   HEADER_LIBRARY = 3
# See meson_impl.py
zlib = [
    { target_name = '@zlib//:zlib', target_type = 2 }
]
libmagma = [
    { target_name = '@fuchsia_sdk//pkg/magma_client', target_type = 2 }
]
libmagma_virt = [
    # No targets
]
